options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # Build Docker image for App 1
  - name: 'gcr.io/cloud-builders/app1'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/raghupothula/microservices/app1:latest', './app1']

  # Push Docker image for App 1 to Artifact Registry
  - name: 'gcr.io/cloud-builders/app1'
    args: ['push', 'us-central1-docker.pkg.dev/raghupothula/microservices/app1:latest']

  # Build Docker image for App 2
  - name: 'gcr.io/cloud-builders/app2'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/raghupothula/microservices/app2:latest', './app2']

  # Push Docker image for App 2 to Artifact Registry
  - name: 'gcr.io/cloud-builders/app2'
    args: ['push', 'us-central1-docker.pkg.dev/raghupothula/microservices/app2:latest']

images:
  - 'us-central1-docker.pkg.dev/raghupothula/microservices/app1:latest'
  - 'us-central1-docker.pkg.dev/raghupothula/microservices/app2:latest'
