steps:
  # Build Docker image for App 1
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcapp1:latest', './app1']

  # Push Docker image for App 1 to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/raghupothula/app1:latest']

  # Build Docker image for App 2
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/raghupothula/app2:latest', './app2']

  # Push Docker image for App 2 to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/raghupothula/app2:latest']

images:
  - 'gcr.io/raghupothula/app1:latest'
  - 'gcr.io/raghupothula/app2:latest'
